services:
  
  db:
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./.db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-u", "admin", "-padmin", "-e", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 12
  
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8060:8080"
  
  tomcat:
    image: tomcat:9.0-jre11
    restart: unless-stopped
    ports:
      - "8050:8080"
    volumes:
      - "./target/demo-0.0.1.war:/usr/local/tomcat/webapps/ROOT.war"
    depends_on:
      db:
        condition: service_healthy
